baseURL = "https://rcvalenzuela.github.io/"
#baseURL = "http://localhost:1313/"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		url = "/about/"
  [[menu.main]]
    name = "Resources"
    identifier = "resources"
    url = "/resources/"

theme = "noteworthy"
title = "René Valenzuela"
